version: "3"
services:
  service:
    image: service
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"